### ISSUE TITLE
update templated README.md

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#11]
- [x] needs RHElement references tokenized
- [x] needs docs updated
- [x] needs 'demo' steps updated

**Comment by starryeyez024** [comment]
I'm desperate to try to test this out, but per this issue there are no commands listed. I was going to try to be helpful and write some docs but I still can't get yeoman to find the generator. In case this is useful, here's an info dump. If it's not useful, disregard and I'll be patiently waiting to do backflips. :)

`$ npm install -g @wcfactory/cli` - works
`$ npm install -g @wcfactory/generator-wcfactory`- works
`$ yo wcfactory` returns:
```
Error wcfactory 
You don't seem to have a generator with the name “wcfactory” installed.
```

`$ yo doctor` returns:
```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ yo version
```

**Comment by btopro** [comment]
try `mkdir stuff && cd stuff && wcfactory init`

**Comment by btopro** [comment]
from there, `wcfactory new` is still finiky bc of some relative path issues that @heyMP and I talked about today

**Comment by btopro** [comment]
@starryeyez024 ok, give it a try now. I just did a mass refactor and documentation update that show resolve the path issues preventing this from working before
