### ISSUE TITLE
support builds and auto compile routines

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#16]
We should support a builds / packages / productions / whatever we name it, we should have a method of building all the smaller elements and rolling them up into 1 directory that could be published. This directory should come with an example integration that will work out of the box in IE11 / iOS 9 / Edge 15/16 / weird stuff and then everyone Evergreen.

http://lrn-button-test.surge.sh/ has an example that will work across all targets by dynamically loading them based on what browser is viewing things.
- [x] support builds / products connotation
- [x] support ES6 and ES5-amd workflows in build step (roll up hits umd but is hit or miss)
- [x] create helper script that figures out which to load and is handed an object to help assess
- [x] #2 add build targets to the CLI w/ ability to add more much like the wcfLibraries

**Comment by ChristianMurphy** [comment]
Rollup can do multiple targets pretty elegantly.
uPortal-web-components landed on this config in the end https://github.com/uPortal-contrib/uPortal-web-components/blob/master/%40uportal/open-id-connect/rollup.config.js

**Comment by btopro** [comment]
Originally the rhelements team had everything in the roll up ( #8 ) and we ran into build issues in development. I opted for polymer cli to do the build process because it's engineered specifically for web component based workflows. That and it would allow people to modify the routine for an element / build target by just touching the json of the file.

Here's an example of one in context https://github.com/elmsln/lrnwebcomponents/blob/master/elements/lrn-button/polymer.json

This won't handle umd (which we still have roll up doing though it fails at times) but it does es6, es5 and amd packaging methods (which are then being pointed to in the demo above)

**Comment by ChristianMurphy** [comment]
> and we ran into build issues in development

Issues with the build process erroring?
Issues with the output?
Or something else?

:notebook: possibly related, to get the build output functioning in uPortal we had to add https://github.com/uPortal-contrib/uPortal-web-components/blob/bb6c9995610703e31479d93814999bff02b0dea4/%40uportal/content-carousel/babel.config.js#L4
https://github.com/github/babel-plugin-transform-custom-element-classes

**Comment by btopro** [comment]
ya it was something around that exact class babel-plugin-transform-custom-element-classes

I dono what the deal was but I'd still pref roll up w/

**Comment by btopro** [comment]
updated which can be found in the demo. it has been optimized to be able to hit the following targets:

Chrome 50+ (69 latest)
Opera 47+ (55 latest)
IOS / Safari 9+ (11 latest)
FF 54+ (63 native)
Edge 15,16,17 (latest)
IE 11

Obscure
Windows Phone 8.1,10
Yandex 14.12

**Comment by ChristianMurphy** [comment]
> updated which can be found in the demo

Where is the demo?

> Chrome 50+ (69 latest)
> ...
> Yandex 14.12

Nice!

**Comment by ChristianMurphy** [comment]
> I'd still pref roll up w/ polymer or the current polymer build w/o roll up given it's pegging specifically to the needs of web components and abstracting these configurations further.

I hear ya, the CLI's provided by Polyer, Vue, etc make things a lot easier.
My concern comes in when there are build systems calling build systems, those connections tend to be fragile.
And I'm not sure that Polyer can handle all the features from Vue, React, Svelte :man_shrugging: 
That's where Rollup and Webpack have an advantage, they do support a wider variety of setups and configurations.

**Comment by btopro** [comment]
https://lrn-button-test.surge.sh on surge so a bit slow to resolve cdn but w/ http2 push on a high powered cdn instead of a free tier one it should smoke

**Comment by ChristianMurphy** [comment]
Ahhh, https://github.com/elmsln/lrnwebcomponents is the demo for this repo?

**Comment by btopro** [comment]
I'm not entirely sure what advantage us supporting Vue / React / Angular would be given that they aren't really web components but libraries that can compile to them as a target, more hybrids then anything (and React isn't at all so I don't like that word).

Svelte your def right it's the odd man out right now. I'd be open for amending the way things build, currently the element definitions are able to fork from how the different commands are executed so it's technically possible now to put in your own build routine per element type https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/init/templates/wcfLibraries

the scripts, dependencies and devDependencies from these package.json's are cloned into the stub elements produced when a `wcfactory new` call is executed in the cli. Polymers are just 1st party currently and the gulp routines are run as part of that but build would be run via lerna across everything at the same time prior to publishing so could deviate if desired (just wouldn't be calling gulp to do it then at least not in its current convention).

Up for refactoring these things, we're working off of modified versions of what RHElements provided, just want to make sure we're able to hit all build targets as we currently can in the experimental script on that demo site and yet still have 1 build routine that sweeps across a well as 1 development method (the part where vue / svelte / etc would start getting complex to manage in here)

**Comment by btopro** [comment]
that is a demo of what's been stamped out. wcfactory seeks to stamp that and provide consistent tooling for managing it regardless of what component library you use.

you can see what we've forked from / are seeking to templatize and enhance here -- https://github.com/rhElements/rhelements

**Comment by ChristianMurphy** [comment]
> I'm not entirely sure what advantage us supporting Vue / React / Angular would be given that they aren't really web components but libraries that can compile to them as a target

So if people want to use these libraries in their component library, they are going to need to eject and custom manage the build?
That seems less than ideal.

> so it's technically possible now to put in your own build routine per element type https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/init/templates/wcfLibraries

:+1:

**Comment by btopro** [comment]
so maybe these would make more sense as build targets, a connotation we're hashing out mentally still.

The advantage of web components is in lack of framework requirement which React / Angular are more world view / frameworks even if they claim to be library focused. Vue / Svelte / Stencil get a bit odd as they are compiled "components" and Vue being the most oddball since it's a mix of the two based on usage.

I'm not opposed to supporting them I'd have to see a working example of how that would function if the goal is to have 1 way of working with components. I want to run `npm run dev` and get an identical authoring experience as a developer. Same for `lerna build` to do the build, same for `wcfactory new` which should walk through the same CLI regardless of library and map conventions to them.

Right now everything we support effectively has:
- a properties connotation
- a data bind connotation (except vanilla/rhelement)
- Class based and can easily have the js, properties, html, css, and hax props files located in the components src folder combined via a simple gulp watch + combine routine (example of those files which are watched and compiled in directory above https://github.com/elmsln/lrnwebcomponents/tree/master/elements/lrn-button/src)

Vue / Svelte / Stencil might make it hard to combine their compile step w/ our current connotation (being able to work in the src folder, separation of concerns, knowing it'll combine correctly).

Not opposed to including the previously mentioned libraries / frameworks with the exception of React and Angular/AngularJS because they aren't web components. Once Angular 9 ships which should be v. component centric it would make sense. Preact is web component compatible so that could work (while React currently is pretty anti components so maybe it could be a build target but not a component in the factory).

Let's hash out how we could get svelta, Stencil and Vue into what's currently here. What would need to change to support these 3, which if we could support these three then the diversity of options would be so high that other things might be easier to approach at that point.

**Comment by ChristianMurphy** [comment]
https://github.com/rollup/rollup-plugin-svelte looks promising for adding in Svelte support

**Comment by btopro** [comment]
scaffolding is there / drastically simplified so we can run this command

**Comment by btopro** [comment]
need to test with a real repo to see the status of and be able to move forward from where it is currently but it's in good shape

**Comment by btopro** [comment]
https://macho-crow.surge.sh/ -- this was produced through running the commands needed to make it happen. Here's the flow which then will need to go into the CLI to be more obvious.
```
mkdir mystuff
wcfactory start #answer things
wcfactory init #create a factory called project1
cd factories/project1 # this needs to happen automatically in the below command
wcfactory new #make an element called cool-stuff
cd elements/cool-stuff #needs a step so that this doesn't need to happen
yarn start # work on your element and make changes
yarn run build # compile the work to be published
cd ../.. # step back to factory root
lerna publish # loops over and will publish everything to npmjs
cd ../.. # step back to conglomerate root
wcfactory build #named test
cd products/builds/test # to access your build which successfully has all elements needed to start your work
```

**Comment by btopro** [comment]
#59 related.
