### ISSUE TITLE
get Storybook 4 working

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#161]
reported in #113 and was known to team but needs documented. Storybook is in place to work but doesn't because of dependencies #90 was previously causing it not to work fully as well

**Comment by cosmicdreams** [comment]
These were the peer dependencies that were reported as missing:

```
warning "@storybook/addon-a11y > @emotion/styled > @emotion/styled-base@0.10.6" has unmet peer dependency "@emotion/core@0.x.x".
warning " > @storybook/polymer@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning " > @storybook/polymer@4.0.4" has unmet peer dependency "lit-html@0.10.0".
warning "@storybook/polymer > @storybook/core@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
[4/4] 📃  Building fresh packages...
```

**Comment by cosmicdreams** [comment]
Adding this line to my root level package.json's devDependencies fixed this for me:

"babel-loader": "^8.0.4",

I also added 

"lit-html": "0.10.0"

I don't know if we should add them to dependencies instead but this storybook 4 to work properly.

**Comment by cosmicdreams** [comment]
@btopro Seeing how this issue is closed, it it fair to assume that a future update will automatically include these dependencies?

**Comment by btopro** [comment]
testing now w/ babel-loader. lit-html comes in with lit-element

**Comment by btopro** [comment]
oh nice it is compiling now.... good one @cosmicdreams

**Comment by btopro** [comment]
fails on something else, which seems workspaces related (yarn workspace that is) which generates circular references to things so.... I dono if storybook can actually work in the current setup but I guess we'll see down the road.

This is not an aspect actively being development at the moment until we actually get our portfolio ported over (about 55% of the way there currently) to be ES modules in this setup via https://github.com/elmsln/lrnwebcomponents

After that, this can start to become more of a priority or if someone wants to try and make it work for them please feel free to do so.

**Comment by cosmicdreams** [comment]
Huh, it works for me.  Maybe I should share my product's package.json.  I think this is the relevant section:
```
"devDependencies": {
    "@babel/core": "7.1.5",
    "@babel/preset-env": "7.1.5",
    "@storybook/addon-a11y": "4.0.4",
    "@storybook/addon-actions": "4.0.4",
    "@storybook/addon-knobs": "4.0.4",
    "@storybook/addon-notes": "4.0.4",
    "@storybook/addon-options": "4.0.4",
    "@storybook/addon-storysource": "4.0.4",
    "@storybook/addon-viewport": "4.0.4",
    "@storybook/addons": "4.0.4",
    "@storybook/cli": "4.0.4",
    "@storybook/polymer": "4.0.4",
    "@webcomponents/webcomponentsjs": "2.1.3",
    "babel-loader": "^8.0.4",
    "babel-plugin-external-helpers": "6.22.0",
    "babel-plugin-transform-es2015-modules-umd": "6.24.1",
    "babel-preset-env": "1.7.0",
    "browser-sync": "2.26.3",
    "chalk": "2.4.1",
    "css-scss": "0.1.1",
    "decomment": "0.9.2",
    "del": "3.0.0",
    "dialog-polyfill": "0.4.10",
    "global": "4.3.2",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-babel": "8.0.0",
    "gulp-clean-css": "3.10.0",
    "gulp-concat-util": "0.5.5",
    "gulp-rename": "1.4.0",
    "gulp-replace": "1.0.0",
    "gulp-sass": "4.0.2",
    "gulp-sequence": "1.0.0",
    "gulp-shell": "0.6.5",
    "gulp-strip-css-comments": "2.0.0",
    "gulp-svg-sprite": "1.5.0",
    "gulp-trim": "1.0.2",
    "husky": "1.1.3",
    "lerna": "3.4.3",
    "lint-staged": "8.0.4",
    "lodash": "4.17.11",
    "lodash.clonedeep": "4.5.0",
    "node-sass": "4.10.0",
    "polymer-build": "3.1.0",
    "polymer-webpack-loader": "2.0.3",
    "prettier": "1.15.0",
    "react": "*",
    "react-dom": "*",
    "requirejs": "2.3.6",
    "rollup": "0.67.0",
    "rollup-plugin-babel": "4.0.3",
    "rollup-plugin-commonjs": "9.2.0",
    "rollup-plugin-terser": "3.0.0",
    "strip-css-comments": "3.0.0",
    "trim": "0.0.1",
    "wct-browser-legacy": "1.0.2",
    "web-component-tester": "6.9.0",
    "webpack": "4.25.1",
    "whatwg-fetch": "3.0.0",
    "yo": "2.0.5",
    "raw-loader": "0.5.1",
    "inquirer-recursive": "0.0.5",
    "gulp-copy": "4.0.1",
    "babel-plugin-transform-custom-element-classes": "0.1.0",
    "jest": "23.6.0",
    "lit-html": "0.10.0"
  },
  "dependencies": {
    "@polymer/lit-element": "0.6.2",
    "@polymer/polymer": "3.1.0",
    "slim-js": "4.0.5"
  },
```

**Comment by cosmicdreams** [comment]
For the record, because of the previous problems we worked through, I upgraded to npm version 6.4.1 and node version 10.10.0

**Comment by btopro** [comment]
Storybook works and displays your elements?

**Comment by cosmicdreams** [comment]
Yep, need a screenshot in order to prove it?

**Comment by btopro** [comment]
@cosmicdreams excellent! Can you do me a favor and make another element (polymer element) and confirm if it works. If it does then make 2 polymer elements (Trying to see if there's still an issue expressed in another thread and I can't replicate this right now bc I have 100s of partly broken things being converted :) )

**Comment by cosmicdreams** [comment]
That did indeed, uncover a number of errors:
<img width="585" alt="screen shot 2018-11-12 at 10 52 16 am" src="https://user-images.githubusercontent.com/852080/48362440-477b0800-e669-11e8-9139-b67f0b53aaa7.png">

This error was discovered while generating a new Polymer element.

<img width="1266" alt="screen shot 2018-11-12 at 10 53 26 am" src="https://user-images.githubusercontent.com/852080/48362441-477b0800-e669-11e8-90bf-7a46e9f4455e.png">

This error was discovered while starting up the storybook again.

**Comment by btopro** [comment]
this isn't surprising and appears to be a common issue w/ node + yarn workspaces + webcomponent based development. 
https://github.com/elmsln/lrnwebcomponents/blob/master/elements/awesome-explosion/demo/index.html#L8 demo's which have https://github.com/elmsln/lrnwebcomponents/blob/master/elements/deduping-fix/deduping-fix.js creates a way for the DOM to cheat on this error (at least in Chrome / FF, Safari doesn't like this).

This is only an error that pops up in local development but obviously an important one. I wonder if we include this dedup fix in the storybook additional assets included if it would help prevent this from happening

**Comment by cosmicdreams** [comment]
I think I might have made a mistake by attempting to fix this issue with yarn install --flat.  Now I get all kinds of "incompatible with requested version" errors and I don't know how to get myself out of that trap.  

Any advice on how to fix?

**Comment by btopro** [comment]
don't do that ;)

Not sure, blow away node_modules directories and don't run install w/ that. It can't work that way bc of the front end deduping per project and the nohoist section in the factory ensures there are multiple copies of things per project (so they can be dev'ed correctly)

**Comment by cosmicdreams** [comment]
Did that. And now am testing with wcfactory 0.5.0.

Looks like we still need to include styled-base into the mix otherwise Storybook doesn't work.

**Comment by cosmicdreams** [comment]
@btopro is this something I can fix myself?  How do I modify the dependencies that are generated for each component?

**Comment by btopro** [comment]
https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/factory/templates/package.json that's the package json that's templated to generate the initial factory files

**Comment by cosmicdreams** [comment]
So... is Storybook working for you yet?

**Comment by btopro** [comment]
messing w/ webpack config stuff and #209 is needed

**Comment by btopro** [comment]
I need to figure out how to make this work and NOT get stuck in loops -

https://github.com/elmsln/lrnwebcomponents/blob/master/.storybook/webpack.config.js#L22-L28

Do you know how I could target `elements/*/*.js` and `elements/*/lib/*.js` but not anything else. I haven't mess w/ webpack much and so I don't know the way to hit this

**Comment by btopro** [comment]
It appears no though I'm not sure why.
```

WARNING in ./node_modules/@emotion/styled/node_modules/@emotion/styled-base/dist/styled-base.browser.esm.js 84:17-31
"export 'withCSSContext' was not found in '@emotion/core'
 @ ./node_modules/@emotion/styled/dist/styled.esm.js
 @ ./node_modules/@storybook/core/dist/client/manager/preview.js
 @ ./node_modules/@storybook/core/dist/client/manager/provider.js
 @ ./node_modules/@storybook/core/dist/client/manager/index.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./.storybook/addons.js ./node_modules/@storybook/core/dist/client/manager/index.js
Child HtmlWebpackCompiler:
                          Asset     Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  558 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.62 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Compiled with warnings.
╭──────────────────────────────────────────────────╮
│                                                  │
│   Storybook 4.0.9 started     
```

**Comment by heyMP** [comment]
The open-wc has a webpack helper that allows for dynamic imports and import.meta.url

https://github.com/open-wc/open-wc/tree/master/packages/webpack

**Comment by btopro** [comment]
pretty sure we have this config from them -- https://github.com/elmsln/lrnwebcomponents/blob/master/.storybook/webpack.config.js

still remains:
```
ERROR in ./elements/code-editor/code-editor.js 194:27
Module parse failed: Unexpected token (194:27)
You may need an appropriate loader to handle this file type.
|   created: function created() {
|     // set this ahead of it being painted into the dom
>     this.__libPath = import.meta.url + "/../../../monaco-editor/min/vs";
|   },
| 
 @ ./elements/code-editor/code-editor.story.js 3:0-46 18:18-28 20:9-19 22:8-18 25:14-24 31:19-29 39:50-60
 @ ./elements sync \.story\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
```

I wish Storybook was platform focused instead of being stuck on WebLack.

**Comment by btopro** [comment]
webpack / storybook updates that I just installed in lrnwebcomponents yeild errors in storybook now instead of failing in webpack layer... though no clue on this one...
```
vendors~main.00096c74f011a1d64960.bundle.js:2555 Uncaught TypeError: Object(...) is not a function
    at vendors~main.00096c74f011a1d64960.bundle.js:2555
    at Object../node_modules/@storybook/components/dist/navigation/MenuLink.js (vendors~main.00096c74f011a1d64960.bundle.js:8949)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/components/dist/index.js (vendors~main.00096c74f011a1d64960.bundle.js:8014)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/addon-knobs/dist/components/Panel.js (vendors~main.00096c74f011a1d64960.bundle.js:3576)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/addon-knobs/dist/register.js (vendors~main.00096c74f011a1d64960.bundle.js:5766)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/addon-knobs/register.js (vendors~main.00096c74f011a1d64960.bundle.js:5797)
```

**Comment by btopro** [comment]
this is finally fixed

**Comment by btopro** [comment]
dependency issue that is a known issue in storybook 4 that they are fixing in storybook 5. for now, we downgrade emotion projects and we'll be golden. the lrnwebcomponents storybook now works (sucks, but it works)
