### ISSUE TITLE
Adding hyperHTML-element factory

### ISSUE THREAD

**Issue by balajiram** [elmsln/WCFactory#196]
Adding support in the tooling system to build custom elements based on hyperHTML [https://github.com/WebReflection/hyperHTML](https://github.com/WebReflection/hyperHTML)

**Comment by btopro** [comment]
so the https://github.com/WebReflection/hyperHTML-Element base class? We'd accept PRs for this and help anyone through what would be required to get it added. From looking at the example this is a good starter issue.

**Comment by btopro** [comment]
adding for reference of where the other templated element files live -- https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/start/templates/templates/libraries

**Comment by btopro** [comment]
would accept contribution but closing due to lack of progress
