### ISSUE TITLE
Leverage Webpack?

### ISSUE THREAD

**Issue by ChristianMurphy** [elmsln/wcfactory#20]
Webpack as some neat tricks with composability which may work out well for wcfactory's setup.

---

One example of how it can be composed is Vue CLI Service.
https://cli.vuejs.org/guide/#cli-service
It offers a core service that pulls in plugins to handle additional functionality like Babel/TypeScript transpiling, Linting, Unit Testing and E2E testing.

Each plugin is a lerna child project
https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue

Each plugin uses webpack chain to extend the configuration
https://github.com/neutrinojs/webpack-chain

And can register a CLI command exposed by the CLI service
https://cli.vuejs.org/dev-guide/plugin-dev.html#service-plugin

---

Or, less change to the current setup, webpack can be used to combine the functionality of the gulp and rollup scripts into a single file.
:notebook: alternative to webpack, gulp scripts could be merged into the existing rollup file

---

Is that style/type of abstraction that would be a good fit for wcfactory?

**Comment by btopro** [comment]
Yes but we'd def have to talk this one through more. I enjoy that currently outside of roll up that elements can be broken off entirely and developed as stand alone, were they needed to switch orgs or fit in other people's workflows not our own it night help more. 

I also have a hate - hate relationship with webpack but if you know her to operate it I can get over that

**Comment by ChristianMurphy** [comment]
Alright maybe a composed version of Rollup?
Or an ever more ambitious version would be adding making web component the target for [Parcel](https://parceljs.org), going more in a zero configuration direction.

**Comment by btopro** [comment]
whatever makes life easier all around. Right now #66 and #59 are going to consolidate the CLI so that it's a single CLI of commands and that you always use it to run tasks, trying to eliminate (as much as possible) commands from the average user that aren't starting with `wcfactory` (which we should move to wcf to simplify characters again)

**Comment by btopro** [comment]
with storybook now working and build flow working I'm not sure what Webpack would net us (other then maybe replacing gulp / roll up's roll in there atm). `polymer build` is doing the dedupping and ensuring assets make sense for front end while still retaining their original location (which https/v2 can stream these down quickly). webpack builds could make sense for static apps, so not against it but I think maybe it would make more sense for end product builds then in what's currently running (or maybe i'm missing something).

If #8 is its own package to make a bit more sense as to where it's going off to do work (or we drop the centralized roll up and just provide 1 command), or have gulp do what roll up does.
