### ISSUE TITLE
Vanilla: exports should be listed last

### ISSUE THREAD

**Issue by cosmicdreams** [elmsln/wcfactory#206]
When generating a vanilla web component today and including it in my app that already had linting enabled i received warnings that warned me not to export the module containing the web component without first defining it.  

I was able to fix by moving the exports to the end of the file.

**Comment by btopro** [comment]
interesting, I was running into issues before doing that (tho may have just been an IDE linting thing i can't remember).

If you could issue a PR to fix this in what's stamped down that'd be great.  Here it is for vanilla -- https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/start/templates/templates/libraries/HTMLElement/HTMLElement.js#L6

Same fix easy enough to apply across the board https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/start/templates/templates/libraries

**Comment by ChristianMurphy** [comment]
> received warnings that warned not to export the module containing the web component without first defining it

Coming from [ESLint](https://eslint.org), [JSHint](https://jshint.com/about/), [TSLint](https://github.com/palantir/tslint), another tool?
Which rule is being triggered?

> I was able to fix by moving the exports to the end of the file.

Something like:

```js
// BAD
export class Component extends HTMLParagraphElement {/*...*/}

function moreCodeBelow () {/*...*/}
```

```js
// GOOD
class Component extends HTMLParagraphElement {/*...*/}

function moreCodeBelow () {/*...*/}

export {Component}
```

Or something different?

**Comment by btopro** [comment]
https://github.com/elmsln/lrnwebcomponents/blob/master/elements/example-hax-element/src/example-hax-element.js#L6 here's an example of what the tooling kicks out. @cosmicdreams is saying linting is claiming that the extension has to happen prior to export and in what's kicked out the export is at the top of the file

**Comment by cosmicdreams** [comment]
OHI, you're fast.

Here's the component in question: https://github.com/cosmicdreams/nerdery-karaoke/blob/master/public/js/youtube-thumbnail.js

This is how the component is generated, before moving the exports to the end of the file.

**Comment by ChristianMurphy** [comment]
Ah, I'm guessing ESLint `no-use-before-define` then? https://eslint.org/docs/rules/no-use-before-define
The linter is correct, according to ECMA-262 `class` declarations are not hoisted.

See:
* http://2ality.com/2015/02/es6-classes-final.html
* https://eslint.org/docs/rules/no-use-before-define
* https://www.ecma-international.org/ecma-262/9.0/index.html#sec-class-definitions

**Comment by btopro** [comment]
good to know. So moving that https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/start/templates/templates/libraries/HTMLElement/HTMLElement.js#L6 export defintion that gets stamped to the end of the files in the templates should work (tho it won't update it in your output monorepo so you'll want to update the templates in `{yourcompanyname}/templates/libraries`

These are separate so that you can fork / add / delete element templates to set your own starting points

**Comment by cosmicdreams** [comment]
@ChristianMurphy yep that was the specific rule.

**Comment by cosmicdreams** [comment]
https://github.com/elmsln/wcfactory/pull/207

**Comment by btopro** [comment]
fixed in tagged commit and fixed across all other template defaults. thank you for reporting chris!
