### ISSUE TITLE
fix nohoist issue with big apps

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#209]
What we have
- interlinking saves space and helps front end... but hurts long term bc of need to constantly dedup things
- this causes bigger apps like HAX to miss timing and fall over :(

What we need
- preinstall hook that runs a script that kills off all node_modules directories in the elements/* workspace
- Then install, but hoisting everything to the top level
- then postinstall - delete all the node_modules in elements/* that lerna just made and create symlinks up to the top

I dono how nicely this will play with installing local dependencies but we'll have to go this route to make our apps stand up. Now that we've got dependencies largely figured out per project it shouldn't be as big a deal

**Comment by btopro** [comment]
- postinstall - delete node_modules/@lrnwebcomponents/* (name of the orgs stuff)
- mkdir elements/* project names
- symlink elements/what-ever/what-ever.js
- symlink elements/what-ever/what-ever/lib

This should then work with builds and serving

**Comment by ChristianMurphy** [comment]
@btopro might be something worth raising to the lerna/yarn teams, handling this upstream will make things like cross platform support and long term maintenance a lot easier.

**Comment by btopro** [comment]
I fixed it in lrnwebcomponents but need to make more generic. oh. my. god.....

and this is a known issue and they haven't addressed, I've been hunting down for weeks :)

**Comment by btopro** [comment]
https://github.com/elmsln/lrnwebcomponents/blob/master/package.json#L24-L38
which calls this on pre - https://github.com/elmsln/lrnwebcomponents/blob/master/scripts/preinstall.sh

and this on post - https://github.com/elmsln/lrnwebcomponents/blob/master/scripts/postinstall.sh

**Comment by btopro** [comment]
Now just need to abstract it so that the @lrnwebcomponents reference is gone and this should work!

**Comment by ChristianMurphy** [comment]
Looking at the approach, it looks like get the dependencies installed once, symlink everywhere else.
Maybe https://pnpm.js.org can help?

**Comment by btopro** [comment]
I have it fixed in LRNWebcomponents but it's very specific to the setup of the factory structure and so the fix here will also be specific to the structure

**Comment by btopro** [comment]
To your other question no the issue had to do was. The mono repo created by wcf not the tooling itself. That bash hack I showed you other day fixes the issue largely though it needs more testing and to be a full blown solution would need to be done in gulp or something more cross platform then bash
