### ISSUE TITLE
Auto dependency updater?

### ISSUE THREAD

**Issue by ChristianMurphy** [elmsln/wcfactory#21]
There are a few services out there that can automatically open pull requests when updated versions of npm dependencies become available.
Two examples are https://greenkeeper.io and https://renovatebot.com/, there are a [few others](https://github.com/marketplace/category/dependency-management)

Would there be interest in leveraging one of these services to help maintain the software over time?

**Comment by btopro** [comment]
Absolutely

**Comment by ChristianMurphy** [comment]
Both Greenkeeper and RenovateApp are good.
Lately I've been leaning toward RenovateApp, because it [is highly configurable](https://renovatebot.com/docs/configuration-options/) and has a neat [preset system](https://renovatebot.com/docs/presets-config/).

Either can be added from the GitHub marketplace https://github.com/marketplace/category/dependency-management

**Comment by btopro** [comment]
sounds great; https://github.com/elmsln/wcfactory/blob/master/renovate.json is in place. feel free to PR against it for any advanced settings you've found useful

**Comment by ChristianMurphy** [comment]
The base config is good. :+1: 
If the PRs get to chatty/annoying this config is good to get the system to back off

```json
{
  "extends": [
    "schedule:weekly",
    "group:all",
    ":rebaseStalePrs",
    ":preserveSemverRanges",
    ":semanticPrefixChore",
    ":ignoreUnstable",
    ":renovatePrefix"
  ]
}
```

It does a once a week update, only of dependencies that are out of semver range.

**Comment by btopro** [comment]
I'll add that into init then since this is supposed to be hands free and adding into the docs afterwards like "you need to manually set this stuff up to make your life happy" wil be good
