### ISSUE TITLE
Move over to yarn workspaces for managing local dependencies

### ISSUE THREAD

**Issue by heyMP** [elmsln/wcfactory#25]
Yarn workspaces seems to be better than Lerna's built-in method of installing shared dependencies in a monorepo.  https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/#managing-dependencies-of-workspaces

As of Lerna 2.0, you can actually integrate workspaces with Lerna pretty seamlessly.  So use yarn workspaces for dependencies and Lerna for publishing.  

Yarn workspaces also would give us the option of managing multiple mono repos which we might be able to add to the cli.

**Comment by ChristianMurphy** [comment]
It's worth trying.

Something to watch out for, yarn workspaces significantly changes how the `node_modules` folders are structured.
The new structure can cause issues with peer dependencies in child packages.

For example ESLint plugins are expected to be a sibling/peer of the ESLint CLI that is running them.

Occasionally, one of the peer dependencies will get hoisted to the top level `node_modules` and the other will be in a child `node_modules`, when this happens both packages are broken.
Hopefully, that is not something that will come up for `wcfactory`.

**Comment by heyMP** [comment]
Thanks for the heads up!  Definitely something to be on the lookout for.

**Comment by heyMP** [comment]
@ChristianMurphy might be helpful for debugging if we run into what you just described.

> If you’re only making changes to a single workspace, use –focus to quickly install sibling dependencies from the registry rather than building all of them from scratch.

https://yarnpkg.com/lang/en/docs/workspaces/#toc-tips-tricks
