### ISSUE TITLE
RHElement (now PatternFly Element) properties support

### ISSUE THREAD

**Issue by castastrophe** [elmsln/wcfactory#285]
Hey @btopro, do you need anything added to the base class for RHElement (now [PatternFly Element](https://github.com/patternfly/patternfly-elements)) properties to be wired up correctly?  I was just playing with the component factory and looking at the great stuff you've done with schemas and storybook.

![screen shot 2018-12-18 at 2 54 56 pm](https://user-images.githubusercontent.com/1840295/50179464-18455f80-02d5-11e9-9299-7ae17f28c9d1.png)

I'll just note here that I'll be opening a PR soon that will include all the project rename updates.  We merged with another project at Red Hat called PatternFly which involved a rebranding.

**Comment by castastrophe** [comment]
I found the getter in the gulpfile!  I'll close this out and open a PR soon with the updated project name!  Thanks.

**Comment by btopro** [comment]
😁😁😁

**Comment by btopro** [comment]
https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/start/templates/templates/libraries/RHElement everything to rename and we will gladly accept the updates
