### ISSUE TITLE
add support for VSCode web-components.json file format

### ISSUE THREAD

**Issue by btopro** [elmsln/WCFactory#325]
This would then allow for auto-completes inside of VSCode. Here is an example:
https://github.com/octref/web-components-examples/blob/master/web-components.json

The tooling makes this even easier to engineer on the fly but we could probably pick up and read in all of the `analysis.json` that polymer analyze leaves around when doing demo / doc work, and then parse out the necessary pieces and assemble the definitions for VSCode pretty quick.

@heyMP thoughts / I feel like this is something you could generate a lot faster then me :)

**Comment by btopro** [comment]
@cosmicdreams also feel free to comment if you have suggestions plz

**Comment by cosmicdreams** [comment]
After a bit of research I found where this idea originated: https://github.com/w3c/webcomponents/issues/776

Looks like many teams are talking about what this will eventually be / whether it's needed / and specifically focusing on VS Code. 

Given that you and the team have standardized on VS Code, I think spending a bit of time to generate a web-components.json file with all the detail the analysis process can keep track of would make it easier for the consumers of this work to do their work.  So, this would be a great feature to add to the wcfactory.

**Comment by btopro** [comment]
I agree; posting what I put in the uPortal discussion referenced here --

I think this could be generated in a way that's agnostic of our tooling that we just leverage if we can assume lerna / a mono-repo of elements (because you need many to even care about this). I think the fastest way to achieve this file would be:

- require an argument as to where to look for the files (possibly pegged to the lerna https://github.com/uPortal-contrib/uPortal-web-components/blob/master/lerna.json#L3 packages variable)
- run polymer analyze (which works on any component not just polymer) to get the meta data / property documentation required
- parse / combine these files to generate the definitions on the fly

Or some other way; whatever gets it automated and built the fastest and if it can happen agnostic o our two projects via some tooling integration then all the better. This could be something that the patternfly and open-wc groups could also utilize as they have similar goals. @castastrophe or @daKmoR may even know of work we could tap into to script this ahead of time.

cross posting all the projects! :)

**Comment by btopro** [comment]
Latest version has this, it was added in and should have referenced :0)
