### ISSUE TITLE
Add functionality to import existing web components into lit-element

### ISSUE THREAD

**Issue by AmyScript** [elmsln/wcfactory#344]
Hello!
I've been building lit-elements using the wcfactory.  I tried to make a lit-element out of a composite of multiple lit-elements and I noticed that when I try to import an existing lit-element under the same factory into the new lit-element in the js module in the src folder, it doesn't work.

A work around I found was to modify the js module in the element folder directly and import it there and modify the render function to include the imported module.  But this seem to contradict the work flow a bit.

Is there anyway we can have that functionality?  Maybe the gulpfile.js in the element folder has to be modified?

**Comment by btopro** [comment]
Can you post how you're referencing these other elements?
Here's an example of how we're doing it between elements -- https://github.com/elmsln/lrnwebcomponents/blob/master/elements/video-player/src/video-player.js#L7

You may find that you need to run `yarn install` from the factory floor (base of the repo.. wow I need a life). This will ensure that pre and post install hooks that help ensure interlinking between projects happens correctly.

Also make sure your on the lastest version of wcfactory as it's fixed some issues revolving around this workflow aspect in recent releases. If your still having issues don't hesitate to post additional error messages and what not.

**Comment by AmyScript** [comment]
ok, I pretty sure I have the latest version of wcfactory as I only downloaded it last week to use.

I am importing the elements like the way you have in the example.  

When you say yarn install from the factory floor, do you mean from my weather-app folder or from the very base folder of the project?  Attach is how my folder structure looks like.
<img width="465" alt="screen shot 2019-01-14 at 11 40 02 am" src="https://user-images.githubusercontent.com/24494020/51126456-2b265380-17f1-11e9-8bd7-b7be08630d18.png">

**Comment by btopro** [comment]
from inside the weather-app directory

**Comment by AmyScript** [comment]
ok I found the issue.  I didn't realize that you have to run yarn start on the element level every time you change an file in the src folder in an element.  I thought that the learna build would have taken care of compiling the new information in each element.

Thanks!

**Comment by btopro** [comment]
ahh. yeah so sorry maybe we should document the workflow a bit more. Here's the general flow that we use:
## add a dependency
- write it into `myfactory/elements/what-ever/package.json` dependencies
- go to `myfactory` and run `yarn install` which will ensure everything is happy dep wise across projects
- now go to `myfactory/elements/what-ever` and run `yarn start` then it'll watch for changes to files in `src` and pull them together into a `myfactory/elements/what-ever/what-ever.js` file

If this makes sense or you feel the docs can be improved around how to use this (or the approach improved upon) please file a PR / issues related to docs or improving it. thx
