### ISSUE TITLE
Support additional licenses that make sense

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#4]

**Comment by btopro** [comment]
from your experience with Apereo, @ChristianMurphy  do you think we should support more then we do currently? BSD 3 clause, MIT, and Apache 2 are the options currently allowed in the generator

**Comment by ChristianMurphy** [comment]
I'd allow anything included in the Apache category A listing for sure https://www.apache.org/legal/resolved.html#category-a

Licenses not listed in category A are iffy,  but sometimes allowable.

I would recommend banning everything in the Apache category X listing https://www.apache.org/legal/resolved.html#what-can-we-not-include-in-an-asf-project-category-x

**Comment by btopro** [comment]
nice, thanks for that list. I added BSD 2 clause. I don't want the list to get out of control but it's good to see all those together
