### ISSUE TITLE
bower@1.8.8: We don't recommend using Bower for new projects

### ISSUE THREAD

**Issue by FDiskas** [elmsln/wcfactory#459]
There is also old school tools like gulp.
Any plans to remove them?

**Comment by btopro** [comment]
couldn't tell you why it complains about bower, we don't use bower in this project other then maybe some legacy polymer elements include bower.json files leading it to throw that complaint. bower isn't used in any part of wcfactory.

As for gulp I have no plans on replacing gulp unless someone wants to take that on.

**Comment by ChristianMurphy** [comment]
Previous discussion about replacing gulp: https://github.com/elmsln/wcfactory/issues/20

**Comment by btopro** [comment]
ahh yes, simplification of these steps would be nice and if it all went rollup or something others agreed upon I wouldn't have an issue with it. This is not an area I'm passionate about. The current tooling flow works and we get a ton accomplished because of it. Happy to have it enhanced though.

**Comment by FDiskas** [comment]
Thanks
