### ISSUE TITLE
default package.json in new factories needs less detail

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/WCFactory#463]
The dependencies block is wrong. It should read like this
```
"dependencies": {
    "@lrnwebcomponents/deduping-fix": "latest",
    "@lrnwebcomponents/hax-body-behaviors": "latest"
  },
```

**Comment by ChristianMurphy** [comment]
@bradallenfisher can you expand on why you want `latest` version pinned?

The reason WCFactory, and most npm packages, do not pin `latest` is that it allows major version updates to happen without any warning, which can cause unexpected breaks in the software.
For getting major updates, services like https://greenkeeper.io and https://renovatebot.com offer the ability to automatically generate PRs when new major/minor versions become available, giving warning, and the opportunity to test before applying the new version.

**Comment by btopro** [comment]
we've been running into issues with latest builds of things since this file is generated by the system. So this isn't a dependency in THIS repo. It's a dependency in the companies produced downstream of here. Might even make sense to remove all dependencies and allow the projects to manage that. I believe the new element package.json files that are generated peg to latest downstream for HAX wiring (if selected) and the dedup fix.

**Comment by ChristianMurphy** [comment]
> we've been running into issues with latest builds of things since this file is generated by the system

Can you expand on this?
What issues are happening?

> Might even make sense to remove all dependencies and allow the projects to manage that

Maybe... Would that require manual intervention to add the dependencies?

> It's a dependency in the companies produced downstream of here

Right, but we want to offer best practice decisions to downstream adopters.
If we use `latest` by default, and that is know to cause issues, the generator has pushed people to use a known risky practice.

**Comment by btopro** [comment]
these things were defined / are currently defined in the factories produced. Then assets of different polymer versions (as one pegged example) get spread everywhere and instantly are out of sync / stored all over the place when doing the initial yarn install of new companies created.

| manual intervention
no, it might help with removing them entirely. I can't honestly recall why I was defining them there to begin with.

| downstream
I'm not sure of the correct way to handle this. dedup is only for local development and not intended for production. It's a stop gap if there's an issue in local dev to not fail but throw happier notices. HAXWiring updates on a regular basis as far as the spec moving forward on that so I'm not sure the best way to handle that. I understand your perspective on pegging to versions for things and I have with everything not those two packages :). So while it's an anti-pattern, I dono how else to handle it to be honest for the hax wiring other then getting versions all over the place

**Comment by ChristianMurphy** [comment]
> get spread everywhere and instantly are out of sync / stored all over the place when doing the initial yarn install of new companies created

This is referring to the `yarn` dependencies?
Would it help to run `yarn upgrade-interactive` while adding a new component? to help folks to upgrade dependencies so all of the polymer versions stay in-sync.

> I can't honestly recall why I was defining them there to begin with.

Okay, I'm all for removing unused dependencies.

> I'm not sure of the correct way to handle this. dedup is only for local development and not intended for production. It's a stop gap if there's an issue in local dev to not fail but throw happier notices.

IIRC, the messages in Chrome about duplicated components are pretty helpful.
Is there another browser giving an unhelpful error message? Would that be something that could be reported to the browser vendor directly, so the work around isn't needed, even for local development?

> HAXWiring updates on a regular basis as far as the spec moving forward on that so I'm not sure the best way to handle that

How many of those updates are major versions?
Using a `^` (any minor or patch) version range is a pretty common solution to allowing version shift without dropping breaking changes on folks.

We could also document how to run `renovate` locally to automatically open PRs when major versions are released.

**Comment by btopro** [comment]
If you don't have the dedup it fails. The dedup library instead catches the failure, outputs it as a notice instead of bricking the page. This allows it to still work in the majority of cases while reporting it to the dev.

if you do `^2.0.08` or `^2.0.10` I see them resolving differently still for some reason :\

**Comment by ChristianMurphy** [comment]
> If you don't have the dedup it fails. The dedup library instead catches the failure, outputs it as a notice instead of bricking the page

:man_shrugging: It the same thing that would happen in prod. It's not an ideal UX, but it has a clear log of what happened, and is easy to fix.


```
2.0.08
    ^
    Is this a typo?
    SemVer numbers usually are not zero prefixed
````

**Comment by btopro** [comment]
really you just spot checked my .8 that I hand typed wrong? ;)

**Comment by btopro** [comment]
k. So this removes specific version numbers (which local node modules / package.json's should be including anyway if they exist). HAX reference removed here as well and allows package.json's to dictate that. Dedup fix pegged to a static version at whatever is latest. This will at least help alleviate the current issue while following @ChristianMurphy recommendations for managing this.
