### ISSUE TITLE
postinstall.sh fails Windows

### ISSUE THREAD

**Issue by andjimrio** [elmsln/WCFactory#488]
Hi!

When I run `yarn install` in factory directory, the process in Windows execute all operations successfully with an error: `bash scripts/postinstall.sh ln: failed to create symbolic link './node_modules': Device or resource busy`.

It is necessary to execute the `ln -s` in cmd format manually: `mklink /J node_modules ..\..\node_modules`. Is it possible to change the script taking into account Linux and Windows?

Thanks.

**Comment by ChristianMurphy** [comment]
```
bash scripts/postinstall.sh ln: failed to create symbolic link './node_modules': Device or resource busy
```

@andjimrio Could you check if any other processes may be holding on to file locks?
https://stackoverflow.com/questions/624154/linux-which-process-is-causing-device-busy-when-doing-umount may help

> Is it possible to change the script taking into account Linux and Windows?

That may be part of the goal of #462

**Comment by jedgar1mx** [comment]
`ln` is a linux command, it will not work on windows. After the `yarn install` you need to create the symlink yourself using `mklink`. Just ran into this problem at my office computer. Hope that helps 😀

**Comment by btopro** [comment]
https://github.com/elmsln/WCFactory/pull/507 are going back and forth about this now in a PR which will fix this :)

**Comment by btopro** [comment]
fixed in latest push on all platforms
