### ISSUE TITLE
element creation errors

### ISSUE THREAD

**Issue by cosmicdreams** [elmsln/WCFactory#490]
I ran into an error with creating elements I ran into this error:

```Error: Cannot find module '/Users/cweber/OpenSource/test-elements/factories//Users/cweber/OpenSource/test-elements/factories/test/package.json'
    at Object.when (~/.config/yarn/global/node_modules/@wcfactory/cli/src/questions/element.js:45:21)
    at promptUser (~/.config/yarn/global/node_modules/@wcfactory/cli/src/utils/commands.js:34:40)
    at <anonymous>
```
Node: 
```
cweber-osx:kraken cweber$ npm --version
n6.9.0
cweber-osx:kraken cweber$ node --version
v8.12.0
```

**Comment by heyMP** [comment]
This might be due to the prompt value having a space in it.  Probably the "name" prompt.

**Comment by cosmicdreams** [comment]
The error I get, both in storybook and when viewing the demo of the element is:
<img width="637" alt="Screen Shot 2019-04-09 at 1 43 59 PM" src="https://user-images.githubusercontent.com/852080/55834004-c3209a00-5acd-11e9-9891-05a0e8bcc5a5.png">

**Comment by ChristianMurphy** [comment]
@cosmicdreams what is the component name?
Is there another similarly named component?

**Comment by btopro** [comment]
this is solved in newer tooling. The issue is package.json in the factory root can't have dependencies or the front-end gets po'ed after the fact
