### ISSUE TITLE
Possible mac install remedies

### ISSUE THREAD

**Issue by btopro** [elmsln/WCFactory#501]
To add the dependencies, you will need to install the following using npm:
minimatch
graceful-fs 4
gulp-util

In terminal (MacOS) run the following commands to install:
sudo npm install -g minimatch
sudo npm install gulp-cli -g
sudo npm install -g graceful-fs

**Comment by ChristianMurphy** [comment]
Maybe they could be declared as `optionalDependencies`?
https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by btopro** [comment]
does that involve an optional install routine we could add to the docs (sounds like a good idea)

**Comment by ChristianMurphy** [comment]
> does that involve an optional install routine

It does, `optionalDependency` installation will be attempted for every install, but if the dependency requires a specific OS https://docs.npmjs.com/files/package.json#os or fails for any other reason, it can skip installation of that dependency without failing the entire install.

**Comment by btopro** [comment]
ahh nice, didn't know that's how that worked!

**Comment by btopro** [comment]
fixed in latest push
