### ISSUE TITLE
storybook start breaks symlinks downstream

### ISSUE THREAD

**Issue by btopro** [elmsln/WCFactory#504]
This is an unfortuante known issue right now w/ our workflow. Because of how our team works when we built this (and a lot of shifting in storybook itself) we haven't focused on storybook as a mid-development / on-going process sorta thing. It's just to communicate out at the end.

So if your in the factory and run `yarn start` it'll fire up storybook but it also has to run the preinstall hooks in order to work correctly (nested node_modules symlinks issue otherwise). SO after your done with the storybook, ensure you always run `yarn install` in order to set things back to working order for individual elements.

**Comment by heyMP** [comment]
Can we run the post install script after storybook starts up?  That would be faster than a full `yarn install`

**Comment by btopro** [comment]
storybook keeps watching and rebuilding. is there a way to fire off a command on exit of the script? if so then yes

**Comment by jedgar1mx** [comment]
you can run the install again after the `yarn start` but not sure if you can listen for `storybook`

**Comment by jedgar1mx** [comment]
I think just adding this to the documentation will be a simple way to solve reduce the confusion.

**Comment by btopro** [comment]
https://wcfactory.js.org/workflow
