### ISSUE TITLE
Adding new library to element with yarn breaks build

### ISSUE THREAD

**Issue by jedgar1mx** [elmsln/WCFactory#511]
I tried adding fontawesome to one of my elements. After doing a `yarn add`, i was not able to get `yarn start` to work properly again. It only seems to affect the element where I tried to add the new module.

Thanks

**Comment by heyMP** [comment]
This is a known issue.  Temp fix is to run `yarn install` from the monorepo location.  We have custom pre/post install scripts that aren't being triggered with yarn add.

**Comment by btopro** [comment]
This would be a good thing to add to our docs as well. The way we add elements
- Edit package.json to add the reference to the right repo location
- run `yarn install` from monorepo / factory root

**Comment by jedgar1mx** [comment]
Yes that would be definitely be very helpful.

**Comment by btopro** [comment]
https://wcfactory.js.org/using-existing-web-components

**Comment by btopro** [comment]
@jedgar1mx keep it coming, thank you for all the feedback and framing things in a way that puts it in our wheel house to respond quickly

**Comment by jedgar1mx** [comment]
Glad i can help, very exited about this project.
