### ISSUE TITLE
Issue with latest docker hub image

### ISSUE THREAD

**Issue by manikandansv** [elmsln/WCFactory#546]
Hi,
Am getting below error while running the latest docker image.

TypeError Plugin: @wcfactory/cli: Cannot read property 'companyDir' of undefined.

Kindly help us in resolving the same.

Thanks
Mani

**Comment by btopro** [comment]
companyDir undefined would suggest that `wcf start` hasn't been run yet as this generates the company directory and what not to establish projects to work out of.
@heyMP created that piece so not sure if there's any issues in the image itself. We tend to just run the dependencies on our own machines.

**Comment by heyMP** [comment]
Yeah that was included for some testing purposes and I haven't taken a look at it in a while.  I would recommend running it locally for now.

**Comment by btopro** [comment]
we should probably remove this file to ensure that people don't try to use it if it's in fact legacy

**Comment by btopro** [comment]
@heyMP we should remove this if we're not going to maintain it so that ppl don't stumble on it and say "the project doesnt work" when really it just doesn't work in the docker container we no longer maintain.

**Comment by heyMP** [comment]
agreed.  I'll move it into another repo for safe keeping.
