### ISSUE TITLE
Help text in generator is confusing, contains typo?

### ISSUE THREAD

**Issue by starryeyez024** [elmsln/wcfactory#56]
When creating a new property, the `? Name` prompt lists several comma-separated words as examples, which I took to mean I could add several values here.

One (quick) way to solve it is just to update the example text to just say,  `? Name (example: firstName)` but later you might want to explore the option to pass in several fields names here. Our generator for the webrh library works this way so maybe we can share that with you if interested. If you pass in 3 different names in the first prompt, it just goes does a for-each loop for all the values passed in, so then you can define field types and such. 

Lastly, `fistName`, is that a typo or do you mean Jack Johnson and Tom O'Leary?
https://www.youtube.com/watch?v=0ZeDd7OyCPE

**Comment by btopro** [comment]
I'd love to see the script, Nikki mentioned that idea but didn't seem possible as I was looking so happy to change that.

Also firstName is how you define hyphenated properties in polymer. That way in js it's firstName but in Dom it's first-name

**Comment by btopro** [comment]
updated to be just 1 item. When you snag that example let's open another issue about implementing the comma separated items way
