### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sher1** [elmsln/WCFactory#608]
Got this error below:
$ yarn global add @wcfactory/cli
yarn global v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Request failed \"404 Not Found\"".
info 
The issue below states that the 5.1.2 package was removed by the author and that there is a 5.1.3 package now
https://github.com/yarnpkg/yarn/issues/6690
I am going to try to do a pull request to see if I can fix this.

**Comment by btopro** [comment]
I anxiously await your PR

**Comment by sher1** [comment]
I obviously don't understand something that is occurring. I was able to install all of the dependencies individually, but still can't install the wcfactory. It seems like there is a problem with the wrong version given from a transitive dependency. More digging to come

**Comment by sher1** [comment]
I had to edit my yarn.lock file which was in ~/.config/yarn/global . It now says
`
har-validator@~5.1.0:
  version "5.1.3"
  resolved "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.3.tgz#1ef89ebd3e4996557675eed9893110dc350fa080"
  integrity sha512-sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==
  dependencies:
    ajv "^6.5.5"
    har-schema "^2.0.0"
`
Problem solved
