### ISSUE TITLE
Error during element's gulp build phase.

### ISSUE THREAD

**Issue by blakemorgan** [elmsln/WCFactory#614]
I'm getting an error when the gulpfile runs after creating an element:
```
at ChildProcess.onexit (/home/btm296/Development/byu-wcf/factories/byu-wcf/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

Has anyone seen this before? These are the options I'm using:

```
? Custom element base class to use lit-element -- data binding ++, very small library. 1 dependencies
? Element name byu-header
? Description / purpose of the element BYU themed page header.
? Do you want to use Sass in this element? Yes
? Do want to use existing Sass dependencies? rh-sass
? Do you want custom properties? (typically yes) Yes
? Auto build support for the HAX authoring system? Yes
? Add a new property? (Y/n) 
? Add a new property? Yes
? Name (eg: title) site-title
? Name (eg: title) site-title
? type of value (the way it is used as data) (Use arrow keys)
? type of value (the way it is used as data) String, text based input
? Default value (leave blank for none) 
? Default value (leave blank for none) 
? Make available in css styles? [name="stuff"] { color: blue; } (y/N) 
? Make available in css styles? [name="stuff"] { color: blue; } No
? Observe changes to this property? (Y/n) 
? Observe changes to this property? Yes
? Add a new property? (Y/n) n
? Add a new property? No
```

It also happens when I don't support the HAX authoring system or when I add more than one property. I haven't found a time when the error doesn't occur.

**Comment by btopro** [comment]
Hmm I'll assume latest version of wcf. What version of node do you have out of curiosity?
We haven't modified the core element creation but several dependencies around it so it's possible. Does it fail to creat the new element or it's just an error during that process yet finishes?

**Comment by blakemorgan** [comment]
Node: 10.16.0
NPM: 6.9.2
Yarn: 1.16.0
WCF: 0.7.3
Gulp CLI: 2.2.0
Gulp  Local: 4.0.2
Polymer CLI: 1.9.10

It creates the element, but when it runs `gulp` after the element creation, the failure happens. Here is some more context:

```
$ bash scripts/postinstall.sh
Done in 6.20s.
yarn run v1.16.0
$ ../../node_modules/.bin/gulp && ../../node_modules/.bin/rollup -c && ../../node_modules/.bin/prettier --ignore-path ../../.prettierignore --write '**/*.{js,json}'
[21:01:25] Using gulpfile ~/Development/byu-wcf/factories/byu-wcf/elements/byu-header/gulpfile.js
[21:01:25] Starting 'default'...
[21:01:25] Starting 'merge'...
[21:01:25] Finished 'merge' after 82 ms
[21:01:25] Starting 'analyze'...
[21:01:26] Finished 'analyze' after 1.74 s
[21:01:26] Starting 'build'...
[21:01:32] 'build' errored after 5.38 s
[21:01:32] Error: exited with error code: 1
    at ChildProcess.onexit (/home/btm296/Development/byu-wcf/factories/byu-wcf/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[21:01:32] 'default' errored after 7.2 s
error Command failed with exit code 1.
```

**Comment by btopro** [comment]
OS? I have seen this before though not in awhile. It should still work going to the element and running yarn start for reference

**Comment by blakemorgan** [comment]
OS: Ubuntu 19.04. It works, but all I see in the browser is this:
![Screenshot from 2019-07-12 21-37-18](https://user-images.githubusercontent.com/9389424/61166600-6e862400-a4ed-11e9-8030-fb4cea5963e2.png)

**Comment by btopro** [comment]
What type of element did you pick for this and would you mind posting the busted element it made somewhere so we can take. Look? Also if you add /demo at tht end of that path you can work on the element. As I said I've seen this on occasion and then reflected in the demo site being borked too but it's usually a temporary thing.

Just a devil of a time figuring out what causes this.

**Comment by blakemorgan** [comment]
I think I found the problem. When I was uploading the element I created to GitHub, prettier ran on commit and threw errors because one of the properties were kebab case. When I remade the component, I made the properties camel case and the build ran successfully.

**Comment by blakemorgan** [comment]
I appeared again. I don't where it came from. Everything was going fine until I ran `lerna run build`. Then I got the same error. Now where ever I run gulp in my element, the error appears again.

**Comment by btopro** [comment]
I use the --no-fail flag I think it is or some equivalent. It's possible I get this error bc I always run my scripts w. That to avoid other known issues some of mine have 😎

**Comment by btopro** [comment]
`--no-bail` is the option
