### ISSUE TITLE
'wcf' is not recognized.... Windows Compatibility

### ISSUE THREAD

**Issue by bstarks** [elmsln/WCFactory#636]
Computer: Windows 10 Home Version
Node.js: version 10.0.0

I ran yarn in a user sub-directory using admin privilages in both a cmd console and a PowerShell console. The PowerShell started the install but always immediately hung before "Resolving packages..." could start. The cmd console produced the below response but, when use of "wcf" was attempted, it always (tried several times) ended with:

'wcf' is not recognized as an internal or external command, operable program or batch file.

I find the wcf.cmd file at

C:\Users\Brent\AppData\Local\Yarn\bin\wcf.cmd

and at 

C:\Users\Brent\AppData\Local\Yarn\cache\v4\npm-@wcfactory-cli-0.7.3-46f8dabef0eec38d55a90a8b7a857373420768f2\node_modules\@wcfactory\cli\.bin\wcf.cmd

indicating the @wcfactory files were downloaded.

// ---   cmd console response   --- //

C:\Users\Brent\Documents\wcf>yarn global add @wcfactory/cli                                               
yarn global v1.17.3                                                                                       
[1/4] Resolving packages...                                                                               
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5                
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js                       
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue                                  
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue                           
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > vinyl-fs > graceful-fs > natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.                                                                                                
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue                
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue         
warning @wcfactory/cli > @wcfactory/generator-wcfactory > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js                                                                                           
[2/4] Fetching packages...                                                                                
[3/4] Linking dependencies...                                                                             
[4/4] Building fresh packages...                                                                          
success Installed "@wcfactory/cli@0.7.3" with binaries:                                                   
      - wcf                                                                                               
Done in 247.49s.                                                                                          
                                                                                                          
C:\Users\Brent\Documents\wcf>wcf --version                                                                
'wcf' is not recognized as an internal or external command, operable program or batch file.

**Comment by btopro** [comment]
I don't think this would cause an issue but here's my output on running said command:
`@wcfactory/cli/0.7.3 darwin-x64 node-v10.15.2`

I'm not sure what global installing of packages on windows looks like @tomsshow @heyMP @ChristianMurphy have you had experience installing a node package globally on a PC and know of any oddities that differed or that we could support better? I know when @tomsshow did get this installed awhile back there were some hiccups for sure but it was installing

**Comment by ChristianMurphy** [comment]
@bstarks Have you added `yarn global bin` to your path?
https://yarnpkg.com/lang/en/docs/cli/global/

Without the yarn bin folder added to path, no CLI packages added via `yarn global add` will be recognized.

**Comment by bstarks** [comment]
@ChristianMurphy: That solved the problem. 

I ran `yarn global bin` in the console to get the global path, then copy & pasted that into the system PATH variable using the dialog. The `wcf` application was available after opening a new console window. 

It would be nice if yarn did this automatically when installed.

Thanks to all.

**Comment by ChristianMurphy** [comment]
It would be nice if yarn set the path automatically.
In the meantime, it might be good to add some information about ensuring path is set to the README or to a FAQ

**Comment by btopro** [comment]
Glad its working for you and thank you @ChristianMurphy for the advisement. I've added a commit to the README to reflect this.
