### ISSUE TITLE
weirdness in lrnwebcomponents factory

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#67]
some odd things:
- [x] lrn-button utilizing materializecss-styles produces an odd build structure where node_modules live nested in other node_modules. Not sure why this happens but it's worth ensuring the tooling isn't the curprit here and that the element's construction is at fault (if that's the case)
- [x] materializecss-styles won't generate it's node_modules depdendencies. the yarn workspace works fine for 2 other elements in the repo tho...

**Comment by btopro** [comment]
materialize was an interesting one. We need to ensure we don't get `flat` level crazy (https://gist.github.com/ds300/158250f230d1825af8a3edd6e7af9cc0 appears to be a script worth testing to auto select latest when in flat mode) but another way of avoiding any issues is that when using our own elements we just need to use `"latest"` when referencing our own stuff.

**Comment by ChristianMurphy** [comment]
> but another way of avoiding any issues is that when using our own elements we just need to use `"latest"` when referencing our own stuff

doesn't lerna take care of updating the version to pinned latest as part of the version/release process?
Or is this something different?

**Comment by btopro** [comment]
something else from what I'm seeing the issue. between elements I just had issues where it would do a local install of the dependency.

So for example.
`lrn-button` has a dependency on `lrn-sub-button` at version `^0.0.10`
`lrn-sub-button` moves on bc of `lerna publish` to version `^0.0.11`. the package.json for `lrn-button` won't be updated (unless there's a flag to do that and then I'd be v happy about it`.

For now I put in the docs to make elements latest (which helps w/ local development). Then for builds it'll figure itself out bc of the `flat` flag in our build process... however you'll get bower style version resolution.. even though it's your own element.
