### ISSUE TITLE
Full component library

### ISSUE THREAD

**Issue by cosmicdreams** [elmsln/wcfactory#68]
Is being able to produce a full component library that includes all of the components within a library a goal for WCFactory.  I don't think I've seen that even though storybook is included.

**Comment by btopro** [comment]
https://github.com/elmsln/wcfactory/issues/66 is a current state of what's

storybook is currently busted in our setup. if you want to see storybook working w/ an element library then see what we've forked from (their storybook works, ours gets mad about polymer and I haven't had time to look at why https://github.com/RHElements/rhelements)

**Comment by btopro** [comment]
and yes it's a goal for sure :)

**Comment by btopro** [comment]
![2018-10-04_08-13-11](https://user-images.githubusercontent.com/329735/46473281-8c2f9b80-c7ad-11e8-8f26-fc9d08597d33.png)

Storybook is working in master, we'll cut a new version once we get things remediated from #59 but it's working!!!
