### ISSUE TITLE
establish company, factory and element context for paths

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#85]
picking up from #83
this has to do w/ where the command is invoked. I think we need to ensure that a "factory context" of sorts can be established. If there is no factory context it needs to complain about needing to be in something.

If the command is invokved from a company (to add a new element that is), then it needs to require a factory context (so then it should ask to pick one). Same for a factory, it has to have a company context in order to work.

Build if invokved from inside of a factory context could skip that question.

- [x] make commands detail which contexts they require (company -> factory -> element)
- [x] work the prompt for input into those that don't have it
- [x] ensure paths are then relative to the closest context possible (so if I require a company, this has to be run from the company or at least move commands to the company before executing them, same for factory and element)
- [x] discover libraries dynamically

**Comment by btopro** [comment]
@heyMP lets talk about this today, I dont think it's that hard just need to plan how to activate it

**Comment by heyMP** [comment]
I'll start with the fallback prompt.

**Comment by btopro** [comment]
commands can now be executed from anywhere on your computer and they'll resolve correctly
