### ISSUE TITLE
yarn install fails (every other)

### ISSUE THREAD

**Issue by btopro** [elmsln/wcfactory#88]
ENOENT: no such file or directory, lstat '.../Documents/git/elmsln/company/factories/lrnwebcomponents/elements/hax-body-behaviors/node_modules/uglify-es'".

**Comment by ChristianMurphy** [comment]
I've run into a similar issue before.
As a work around, I set up a custom task that calls `rm -rf node_modules && yarn`.

**Comment by btopro** [comment]
looking like it might have been related to a local dependency conflicting w/ the global. When I cleaned up the package.json of the offending element it went away
