### ISSUE TITLE
Add variable for 'repo name' prefix when naming elements

### ISSUE THREAD

**Issue by heyMP** [elmsln/wcfactory#9]
![screen shot 2018-09-20 at 10 52 39 am](https://user-images.githubusercontent.com/3428964/45827026-9e94da00-bcc3-11e8-9210-5e9cdf587c2c.png)

https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/app/templates/package.json#L2

**Comment by btopro** [comment]
should go in the element creation yo but read off of a centralized configuration @castastrophe mentioned. Paraphrased mentality I think we should adopt: "No one is going to adopt this if they have to hit enter more than they need to" :)

**Comment by btopro** [comment]
fixed

**Comment by btopro** [comment]
variable is `<%= org %>` for organization (without the @ symbol so we can control it more elsewhere)
also added is `<%= gitRepo %>` for a full git repo address so we can script that during install as well as in the directions
